language: r

before_script:
  - sudo apt-get install -y ghostscript
  - sudo apt-get install qpdf

bioc_packages:
  - Biostrings
  - GenomeInfoDb
  - GenomicAlignments
  - GenomicRanges
  - BiocGenerics
  - IRanges
  - Rsamtools
  - rtracklayer
  - S4Vectors
  - BSgenome
  - BSgenome.Hsapiens.UCSC.hg19

addons:
    apt:
        packages:
        - ghostscript
after_success:
  - Rscript -e 'covr::codecov()'
