language: r

bioc_packages:
  - Biostrings
  - GenomeInfoDb
  - GenomicAlignments
  - GenomicRanges
  - BiocGenerics
  - IRanges
  - Rsamtools
  - rtracklayer
  - S4Vectors
  - BSgenome
  - BSgenome.Hsapiens.UCSC.hg19


after_success:
  - Rscript -e 'covr::codecov()'
